apiVersion: v1
kind: Service
metadata:
  name: mointerface-service
spec:
  type: NodePort
  selector:
    app: mointerface
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001