import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import {AppRoot} from "@telegram-apps/telegram-ui";

const inter = Libre_Franklin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <AppRoot>
          {children}
      </AppRoot>
      </body>
      </html>

  );
}