import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import {AppRoot} from "@telegram-apps/telegram-ui";
import Head from "next/head";
import React from "react";
import Script from "next/script";

const inter = Libre_Franklin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <Head>
          <link rel="preload" href="/bg.svg" as="image"/>
          <link rel="preload" href="/text.svg" as="image"/>
          <link rel="preload" href="/comingsoon.svg" as="image"/>
          <link rel="preload" href="/coin.svg" as="image"/>
      </Head>
      <Script src="https://telegram.org/js/telegram-web-app.js"></Script>
      <body className={inter.className}>
      <AppRoot>
          {children}
      </AppRoot>
      </body>
      </html>

  );
}