name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short commit SHA
        id: vars
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV


      - name: Build and push Docker image with commit SHA and latest tag
        run: |
          docker build -t andreyzuikov/mointerface:${{ env.GITHUB_SHA }} .
          docker tag andreyzuikov/mointerface:${{ env.GITHUB_SHA }} andreyzuikov/mointerface:latest
          docker push andreyzuikov/mointerface:latest
          docker push andreyzuikov/mointerface:${{ env.GITHUB_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Install Yandex Cloud CLI
        run: |
          curl -sL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          yc --version

      - name: Verify Yandex Cloud CLI Installation
        run: |
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          which yc
          yc --version
          

      - name: Configure Yandex Cloud CLI
        run: |
          mkdir -p ~/.config/yandex-cloud
          echo "${{ secrets.YC_CREDENTIALS }}" > ~/.config/yandex-cloud/credentials.json

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          echo "${{ secrets.YANDEX_TOKEN }}" > /tmp/yandex-cloud-token.txt
          yc config set token $(cat /tmp/yandex-cloud-token.txt)
          yc config set cloud-id ${{ secrets.YANDEX_CLOUDID }}
          yc config set folder-id ${{ secrets.YANDEX_FOLDERID }}
          yc managed-kubernetes cluster get-credentials --id ${{ secrets.K8S_CLUSTER_ID }} --external --force

      - name: Update Docker Image in Deployment YAML
        run: |
          sed -i "s|image: andreyzuikov/mointerface:.*|image: andreyzuikov/mointerface:${GITHUB_SHA}|g" k8s/deployment.yaml


      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml